version: "3.7"
services:
  minecraft:
    image: itzg/minecraft-server:adopt11
    ports:
        - 25565:25565
    volumes:
        - ./data:/data
    environment:
        TYPE: PAPER
        EULA: "true"
        CLASSPATH: /data/plugins